# Generated by Django 5.2 on 2025-05-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_enable_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('view_all_sales', 'Can view all sales'), ('edit_sale', 'Can edit sale records')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('view_all_services', 'Can view all services'), ('edit_service', 'Can edit service records')]},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
