# Generated by Django 5.2 on 2025-05-05 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_sale_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
