# Generated by Django 5.2 on 2025-05-05 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
