# Generated by Django 5.2 on 2025-05-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_service_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток на складе')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'permissions': [('view_all_parts', 'Can view all parts'), ('edit_part', 'Can edit parts')],
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_parts', to='salon.part', verbose_name='Запчасть')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_parts', to='salon.service', verbose_name='Сервисный заказ')),
            ],
            options={
                'verbose_name': 'Запчасть в заказе',
                'verbose_name_plural': 'Запчасти в заказах',
                'unique_together': {('service', 'part')},
            },
        ),
    ]
